# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_pd=pd.read_csv('../starter_code/output_data/weather_data.csv')
del weather_pd['Unnamed: 0']
weather_pd.head()

,Country,City,Lat,Lang,Temp,Cloud,Wind speed,Humidity,Date
0,CA,Thompson,55.74,-97.86,14.00,5,10.29,61,1586451583
1,RU,Tiksi,71.69,128.87,34.79,100,37.20,86,1586451584
2,GL,Ilulissat,69.22,-51.10,24.80,5,5.82,53,1586451585
3,BR,Arraial do Cabo,-22.97,-42.03,77.00,40,23.04,61,1586451586
4,NZ,Kaitangata,-46.28,169.85,48.00,98,10.13,82,1586451587

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
locations=weather_pd[["Lat","Lang"]]
weight=weather_pd["Humidity"].astype(float)
max_humidity=weight.max()

In [4]:
fig=gmaps.figure()
heat_layer=gmaps.heatmap_layer(locations,weights=weight,
                               dissipating=False,max_intensity=max_humidity,point_radius=1)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [15]:
fitted_cities=weather_pd.loc[(weather_pd["Temp"]>70) & (weather_pd['Temp']<80) & 
                             (weather_pd['Cloud']==0) & (weather_pd['Wind speed']<10),:]
fitted_cities=fitted_cities.dropna(how='any')
fitted_cities.reset_index(inplace=True)
del fitted_cities["index"]
fitted_cities.head()

,Country,City,Lat,Lang,Temp,Cloud,Wind speed,Humidity,Date
0,AR,San Vicente,-26.62,-54.13,72.43,0,4.97,30,1586451784
1,IT,Florence,43.77,11.25,75.20,0,3.36,16,1586451720
2,PY,Juan de Ayolas,-27.40,-56.90,73.27,0,9.51,39,1586451963
3,PK,Gwadar,25.12,62.33,79.30,0,8.81,69,1586451974
4,IN,Honāvar,14.28,74.45,78.51,0,4.05,72,1586451976

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [16]:
hotels=[]
for i in range(len(fitted_cities)):
    lattitude=fitted_cities.loc[i]['Lat']
    langitude=fitted_cities.loc[i]['Lang']
    params={
        "location":f'{lattitude},{langitude}',
        "radius":5000,
        'type':'hotel',
        "key":g_key
    }
    
    base_url="https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    response=requests.get(base_url,params=params).json()
    try:
        hotels.append(response['results'][0]['name'])
    except:
        hotels.append("")
fitted_cities["Hotel Name"]=hotels

fitted_cities.head()

,Country,City,Lat,Lang,Temp,Cloud,Wind speed,Humidity,Date,Hotel Name
0,AR,San Vicente,-26.62,-54.13,72.43,0,4.97,30,1586451784,San Pedro
1,IT,Florence,43.77,11.25,75.20,0,3.36,16,1586451720,Florence
2,PY,Juan de Ayolas,-27.40,-56.90,73.27,0,9.51,39,1586451963,Ayolas
3,PK,Gwadar,25.12,62.33,79.30,0,8.81,69,1586451974,Gwadar
4,IN,Honāvar,14.28,74.45,78.51,0,4.05,72,1586451976,Honnavar

In [19]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in fitted_cities.iterrows()]
locations = fitted_cities[["Lat", "Lang"]]

In [20]:
# Add marker layer ontop of heat map
markers=gmaps.marker_layer(locations)
fig.add_layer(markers)
fig

# Display Map

Figure(layout=FigureLayout(height='420px'))